services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: iQbe
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - /node_modules
      - .:/iQbe
  db:
    image: mysql:9.1
    container_name: iQbe-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - iqbe-data:/var/lib/mysql
    networks:
      - iqbe-network

volumes:
  iqbe-data:
    driver: local

networks:
  iqbe-network:
    driver: bridge
