version: "3.9"
services:
  app: 
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: iQbe
    restart: always
    ports:
      - "9000:9000"
    depends_on: 
      - db
    volumes:
      - /node_modules
      - .:/iQbe
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql/data
    networks:
      - mysql-network

volumes:
  db_data:
    driver: local

networks:
  mysql-network:
    driver: bridge
    