packages:
  - packages/frontend
  - packages/backend
  - packages/api

ignoredBuiltDependencies:
  - esbuild

overrides:
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  nodemailer@<7.0.7: '>=7.0.7'
  nodemailer@<=7.0.10: '>=7.0.11'
  tmp@<=0.2.3: '>=0.2.4'
