/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbookRouteImport } from './routes/workbook'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FavoriteRouteImport } from './routes/favorite'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkbookWidRouteImport } from './routes/workbook.$wid'
import { Route as MylistMidRouteImport } from './routes/mylist.$mid'

const WorkbookRoute = WorkbookRouteImport.update({
  id: '/workbook',
  path: '/workbook',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteRoute = FavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbookWidRoute = WorkbookWidRouteImport.update({
  id: '/$wid',
  path: '/$wid',
  getParentRoute: () => WorkbookRoute,
} as any)
const MylistMidRoute = MylistMidRouteImport.update({
  id: '/mylist/$mid',
  path: '/mylist/$mid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/favorite': typeof FavoriteRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/practice': typeof PracticeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/setting': typeof SettingRoute
  '/welcome': typeof WelcomeRoute
  '/workbook': typeof WorkbookRouteWithChildren
  '/mylist/$mid': typeof MylistMidRoute
  '/workbook/$wid': typeof WorkbookWidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/favorite': typeof FavoriteRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/practice': typeof PracticeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/setting': typeof SettingRoute
  '/welcome': typeof WelcomeRoute
  '/workbook': typeof WorkbookRouteWithChildren
  '/mylist/$mid': typeof MylistMidRoute
  '/workbook/$wid': typeof WorkbookWidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/favorite': typeof FavoriteRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/practice': typeof PracticeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/setting': typeof SettingRoute
  '/welcome': typeof WelcomeRoute
  '/workbook': typeof WorkbookRouteWithChildren
  '/mylist/$mid': typeof MylistMidRoute
  '/workbook/$wid': typeof WorkbookWidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/favorite'
    | '/history'
    | '/login'
    | '/not-found'
    | '/practice'
    | '/reset-password'
    | '/search'
    | '/setting'
    | '/welcome'
    | '/workbook'
    | '/mylist/$mid'
    | '/workbook/$wid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/favorite'
    | '/history'
    | '/login'
    | '/not-found'
    | '/practice'
    | '/reset-password'
    | '/search'
    | '/setting'
    | '/welcome'
    | '/workbook'
    | '/mylist/$mid'
    | '/workbook/$wid'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/favorite'
    | '/history'
    | '/login'
    | '/not-found'
    | '/practice'
    | '/reset-password'
    | '/search'
    | '/setting'
    | '/welcome'
    | '/workbook'
    | '/mylist/$mid'
    | '/workbook/$wid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  FavoriteRoute: typeof FavoriteRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  PracticeRoute: typeof PracticeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingRoute: typeof SettingRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkbookRoute: typeof WorkbookRouteWithChildren
  MylistMidRoute: typeof MylistMidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbook': {
      id: '/workbook'
      path: '/workbook'
      fullPath: '/workbook'
      preLoaderRoute: typeof WorkbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite': {
      id: '/favorite'
      path: '/favorite'
      fullPath: '/favorite'
      preLoaderRoute: typeof FavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbook/$wid': {
      id: '/workbook/$wid'
      path: '/$wid'
      fullPath: '/workbook/$wid'
      preLoaderRoute: typeof WorkbookWidRouteImport
      parentRoute: typeof WorkbookRoute
    }
    '/mylist/$mid': {
      id: '/mylist/$mid'
      path: '/mylist/$mid'
      fullPath: '/mylist/$mid'
      preLoaderRoute: typeof MylistMidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkbookRouteChildren {
  WorkbookWidRoute: typeof WorkbookWidRoute
}

const WorkbookRouteChildren: WorkbookRouteChildren = {
  WorkbookWidRoute: WorkbookWidRoute,
}

const WorkbookRouteWithChildren = WorkbookRoute._addFileChildren(
  WorkbookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  FavoriteRoute: FavoriteRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  PracticeRoute: PracticeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingRoute: SettingRoute,
  WelcomeRoute: WelcomeRoute,
  WorkbookRoute: WorkbookRouteWithChildren,
  MylistMidRoute: MylistMidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
