version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iqbe-dev
    command: sleep infinity
    depends_on:
      - db
    volumes:
      - ../:/iQbe:cached
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - dev.env
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql:9.1
    container_name: iqbe-db-dev
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ../db/conf.d:/etc/mysql/conf.d
    env_file:
      - dev.env

volumes:
  mysql-data:
