import createClient from "openapi-fetch";
import type { paths } from "@/gen/schema"; // generated by openapi-typescript
import ApiError from "./ApiError";

const client = createClient<paths>({ baseUrl: "http://localhost:9000/api/v2" });

export { ApiError };
export default client;